"""sandbox/build_space.py — assemble a self-contained Hugging Face Space directory.

A Hugging Face Space is its own git repo, so it must carry everything it imports.
This packages a *flat* deploy directory at ``sandbox/space/`` by copying:

    space/
    ├── README.md                 # generated, with the HF Space YAML front-matter
    ├── app.py                    # the sandbox app (unchanged — it is layout-agnostic)
    ├── requirements.txt          # gradio + numpy + pandas (no torch/LLM libs)
    ├── validate_submission.py    # the official validator (vendored)
    ├── src/                      # the pure scoring package rank.py imports (no precompute/)
    ├── artifacts/                # the ids-restricted artifact subset (~260 KB)
    └── sample_candidates.jsonl   # the 100 bundled records (~560 KB)

The result is < 1 MB and needs no Git LFS. ``app.py`` finds ``src`` beside itself in
this flat layout, exactly as it finds it one level up inside the repo.

    python sandbox/build_space.py
    # then: create a Gradio Space on huggingface.co and push sandbox/space/ to it.

This is a *prep* tool — never run at sandbox runtime.
"""

from __future__ import annotations

import shutil
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent
SPACE = HERE / "space"

SDK_VERSION = "5.50.0"  # keep in sync with sandbox/requirements.txt

README = f"""---
title: Redrob Ranker Sandbox
emoji: 🎯
colorFrom: indigo
colorTo: blue
sdk: gradio
sdk_version: {SDK_VERSION}
app_file: app.py
pinned: false
---

# redrob-ranker — offline sandbox

Runs the **offline** top-100 candidate ranker on a bundled 100-candidate sample
(or your own uploaded JSONL) straight to a ranked table and a CSV that passes the
challenge's official `validate_submission.py`.

**Golden rule:** the rank path never touches a network or an LLM. All the heavy
understanding (embeddings + LLM signal extraction) was precomputed offline and
baked into `artifacts/`; this app only loads those files and computes a
transparent weighted score — no API key, no model, no network at rank time.

The bundled sample is the strongest fits plus a deliberate spread of traps (a
honeypot, CV-bait, consulting-only careers, job-hoppers). Watch the genuine fits
rise and the traps sink — the honeypot is forced to `0.000`.

Generated by `sandbox/build_space.py` from the main repo. Do not edit here; edit
the source and re-run the builder.
"""


def _copy_src(dst_src: Path) -> None:
    """Copy the ``src`` package, minus caches and the offline-only ``precompute`` CLIs.

    ``precompute/`` is never imported by the rank path (the golden rule), so it is
    excluded to keep the Space minimal and unambiguous about what runs.
    """
    shutil.copytree(
        REPO_ROOT / "src",
        dst_src,
        ignore=shutil.ignore_patterns("__pycache__", "precompute"),
    )


def main() -> None:
    if SPACE.exists():
        shutil.rmtree(SPACE)
    SPACE.mkdir(parents=True)

    shutil.copy2(HERE / "app.py", SPACE / "app.py")
    shutil.copy2(HERE / "requirements.txt", SPACE / "requirements.txt")
    shutil.copy2(REPO_ROOT / "validate_submission.py", SPACE / "validate_submission.py")
    shutil.copy2(HERE / "sample_candidates.jsonl", SPACE / "sample_candidates.jsonl")
    shutil.copytree(HERE / "artifacts", SPACE / "artifacts")
    _copy_src(SPACE / "src")
    (SPACE / "README.md").write_text(README, encoding="utf-8")

    total = sum(p.stat().st_size for p in SPACE.rglob("*") if p.is_file())
    print(f"assembled {SPACE.relative_to(REPO_ROOT)} ({total / 1024:.0f} KB)")
    print("next: create a Gradio Space on huggingface.co, then from sandbox/space/:")
    print("  git init && git remote add origin https://huggingface.co/spaces/<you>/<name>")
    print("  git add . && git commit -m 'offline ranker sandbox' && git push -u origin main")


if __name__ == "__main__":
    main()
